version: '3'
services:

  socks5:
    restart: always
    image: serjs/go-socks5-proxy
    ports:
      - "${PROXY_PORT:-1080}:1080"
    environment:
      - PROXY_USER=${PROXY_USER}
      - PROXY_PASSWORD=${PROXY_PASSWORD}
      - PROXY_PORT=${PROXY_PORT}
